spring:
  datasource:
          url:jdbc:mysql://localhost:3306/bimbingan_belajar_dev
          username:root
          password:1234

server:
  port:8989

spring:
  datasource:
      hikari:
        connection-timeout:20000
              minimum-idle:5
         maximum-pool-size:12
              idle-timeout:300000
              max-lifetime:1200000

spring:
   jpa:
   properties:
     hibernate:
          dialect:org.hibernate.dialect.MySQLDialect
       format_sql:true
               id:
                new_generator_mappings:false


logging:
  level:
    org:
    hibernate:
           SQL=:DEBUG
         type:
          descriptor:
                  sql:
                  BasicBinder:TRACE 

eintrusty:
      app:
        regex1://
        regex2:;
        jwtSecret:sewrtnjlbadaydyw
        jwtExpiration:86400